
package rm.rmwebservice.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "RmWeb", targetNamespace = "http://webservice.rm/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RmWeb {


    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "shutdown", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.Shutdown")
    @ResponseWrapper(localName = "shutdownResponse", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.ShutdownResponse")
    public boolean shutdown();

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "start", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.Start")
    @ResponseWrapper(localName = "startResponse", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.StartResponse")
    public int start();

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     * @throws DeadlockException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addFlight", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.AddFlight")
    @ResponseWrapper(localName = "addFlightResponse", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.AddFlightResponse")
    public boolean addFlight(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3)
        throws DeadlockException_Exception
    ;

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     * @throws DeadlockException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addCars", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.AddCars")
    @ResponseWrapper(localName = "addCarsResponse", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.AddCarsResponse")
    public boolean addCars(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3)
        throws DeadlockException_Exception
    ;

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     * @throws DeadlockException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addRooms", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.AddRooms")
    @ResponseWrapper(localName = "addRoomsResponse", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.AddRoomsResponse")
    public boolean addRooms(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3)
        throws DeadlockException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     * @throws DeadlockException_Exception
     * @throws NumberFormatException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "newCustomer", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.NewCustomer")
    @ResponseWrapper(localName = "newCustomerResponse", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.NewCustomerResponse")
    public int newCustomer(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws DeadlockException_Exception, NumberFormatException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     * @throws DeadlockException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteFlight", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.DeleteFlight")
    @ResponseWrapper(localName = "deleteFlightResponse", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.DeleteFlightResponse")
    public boolean deleteFlight(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1)
        throws DeadlockException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     * @throws DeadlockException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteCars", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.DeleteCars")
    @ResponseWrapper(localName = "deleteCarsResponse", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.DeleteCarsResponse")
    public boolean deleteCars(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws DeadlockException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     * @throws DeadlockException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteRooms", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.DeleteRooms")
    @ResponseWrapper(localName = "deleteRoomsResponse", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.DeleteRoomsResponse")
    public boolean deleteRooms(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws DeadlockException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     * @throws DeadlockException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteCustomer", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.DeleteCustomer")
    @ResponseWrapper(localName = "deleteCustomerResponse", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.DeleteCustomerResponse")
    public boolean deleteCustomer(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1)
        throws DeadlockException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     * @throws DeadlockException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryFlight", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.QueryFlight")
    @ResponseWrapper(localName = "queryFlightResponse", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.QueryFlightResponse")
    public int queryFlight(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1)
        throws DeadlockException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     * @throws DeadlockException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryCars", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.QueryCars")
    @ResponseWrapper(localName = "queryCarsResponse", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.QueryCarsResponse")
    public int queryCars(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws DeadlockException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     * @throws DeadlockException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryRooms", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.QueryRooms")
    @ResponseWrapper(localName = "queryRoomsResponse", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.QueryRoomsResponse")
    public int queryRooms(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws DeadlockException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws DeadlockException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryCustomerInfo", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.QueryCustomerInfo")
    @ResponseWrapper(localName = "queryCustomerInfoResponse", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.QueryCustomerInfoResponse")
    public String queryCustomerInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1)
        throws DeadlockException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     * @throws DeadlockException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryFlightPrice", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.QueryFlightPrice")
    @ResponseWrapper(localName = "queryFlightPriceResponse", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.QueryFlightPriceResponse")
    public int queryFlightPrice(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1)
        throws DeadlockException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     * @throws DeadlockException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryCarsPrice", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.QueryCarsPrice")
    @ResponseWrapper(localName = "queryCarsPriceResponse", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.QueryCarsPriceResponse")
    public int queryCarsPrice(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws DeadlockException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     * @throws DeadlockException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryRoomsPrice", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.QueryRoomsPrice")
    @ResponseWrapper(localName = "queryRoomsPriceResponse", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.QueryRoomsPriceResponse")
    public int queryRoomsPrice(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws DeadlockException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     * @throws DeadlockException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "reserveFlight", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.ReserveFlight")
    @ResponseWrapper(localName = "reserveFlightResponse", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.ReserveFlightResponse")
    public boolean reserveFlight(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2)
        throws DeadlockException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     * @throws DeadlockException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "reserveCar", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.ReserveCar")
    @ResponseWrapper(localName = "reserveCarResponse", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.ReserveCarResponse")
    public boolean reserveCar(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2)
        throws DeadlockException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     * @throws DeadlockException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "reserveRoom", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.ReserveRoom")
    @ResponseWrapper(localName = "reserveRoomResponse", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.ReserveRoomResponse")
    public boolean reserveRoom(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2)
        throws DeadlockException_Exception
    ;

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "itinerary", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.Itinerary")
    @ResponseWrapper(localName = "itineraryResponse", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.ItineraryResponse")
    public boolean itinerary(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        List<Object> arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        boolean arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        boolean arg5);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "customerExist", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.CustomerExist")
    @ResponseWrapper(localName = "customerExistResponse", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.CustomerExistResponse")
    public boolean customerExist(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "customerReserveWrite", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.CustomerReserveWrite")
    @ResponseWrapper(localName = "customerReserveWriteResponse", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.CustomerReserveWriteResponse")
    public boolean customerReserveWrite(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        int arg4);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "dump", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.Dump")
    @ResponseWrapper(localName = "dumpResponse", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.DumpResponse")
    public void dump(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     * @throws DeadlockException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeReservation", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.RemoveReservation")
    @ResponseWrapper(localName = "removeReservationResponse", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.RemoveReservationResponse")
    public boolean removeReservation(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2)
        throws DeadlockException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     * @throws InvalidTransactionException_Exception
     * @throws TransactionAbortedException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "commit", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.Commit")
    @ResponseWrapper(localName = "commitResponse", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.CommitResponse")
    public boolean commit(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws InvalidTransactionException_Exception, TransactionAbortedException_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws InvalidTransactionException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "abort", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.Abort")
    @ResponseWrapper(localName = "abortResponse", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.AbortResponse")
    public void abort(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws InvalidTransactionException_Exception
    ;

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "realShutdown", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.RealShutdown")
    @ResponseWrapper(localName = "realShutdownResponse", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.RealShutdownResponse")
    public void realShutdown();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     * @throws DeadlockException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "newCustomerWithId", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.NewCustomerWithId")
    @ResponseWrapper(localName = "newCustomerWithIdResponse", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.NewCustomerWithIdResponse")
    public boolean newCustomerWithId(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1)
        throws DeadlockException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "startWithId", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.StartWithId")
    @ResponseWrapper(localName = "startWithIdResponse", targetNamespace = "http://webservice.rm/", className = "rm.rmwebservice.client.StartWithIdResponse")
    public int startWithId(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
