
package rm.rmwebservice.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "RmWebService", targetNamespace = "http://webservice.rm/", wsdlLocation = "http://localhost:9899/RmWeb?wsdl")
public class RmWebService
    extends Service
{

    private final static URL RMWEBSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(rm.rmwebservice.client.RmWebService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = rm.rmwebservice.client.RmWebService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:9899/RmWeb?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:9899/RmWeb?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        RMWEBSERVICE_WSDL_LOCATION = url;
    }

    public RmWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }
    
    public RmWebService() {
        super(RMWEBSERVICE_WSDL_LOCATION, new QName("http://webservice.rm/", "RmWebService"));
    }

    /**
     * 
     * @return
     *     returns RmWeb
     */
    @WebEndpoint(name = "RmWebPort")
    public RmWeb getRmWebPort() {
        return super.getPort(new QName("http://webservice.rm/", "RmWebPort"), RmWeb.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RmWeb
     */
    @WebEndpoint(name = "RmWebPort")
    public RmWeb getRmWebPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.rm/", "RmWebPort"), RmWeb.class, features);
    }

}
