
package rm.rmwebservice.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "TransactionAbortedException", targetNamespace = "http://webservice.rm/")
public class TransactionAbortedException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private TransactionAbortedException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public TransactionAbortedException_Exception(String message, TransactionAbortedException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public TransactionAbortedException_Exception(String message, TransactionAbortedException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: rm.rmwebservice.client.TransactionAbortedException
     */
    public TransactionAbortedException getFaultInfo() {
        return faultInfo;
    }

}
